### PR TITLE
Pin influxdb image to v1.8.4 in docker-compose.yml

### PR DESCRIPTION
**Pull request by mauvehed**
My Varken recently blew up because Influxdb was mistakenly upgraded to v2.0. The only errors in the logs were authentication failures. After some debugging and documentation reading, I discovered the incompatible version of Influxdb.

I know v2.0 support is around the corner (#195), but this could save other people the same problems in the future. I'd start pinning specific supported image versions for all required containers.

### CODE REVIEW

**Comment by samwiseg0** [comment]
Please merge into develop instead.

**Comment by pbarone** [comment]
I created a bug (#199) before seeing this pull request as I faced exactly the same issue

**Comment by samwiseg0** [comment]
Going to close this as the rebase messed up the changes. I have updated develop with `image: influxdb:1.8.4`

**Comment by mauvehed** [comment]
> Going to close this as the rebase messed up the changes. I have updated develop with `image: influxdb:1.8.4`

What could I have done more appropriately? Asking for feedback/instruction.

**Pull request closed without merging**
