### PR TITLE
Add Ombi Issues

### LINKED ISSUE #70: [Feature Request] Add issues from Ombi
**Is your feature request related to a problem? Please describe.**
I get notifications from Ombi for issues but either don't have time to get to them or forget about them. A single point of information located on the dashboard of title and type or at minimum a count of open issues would be useful. 

**Describe the solution you'd like**
Add ability to grab issues from Ombi. At minimum a count would be good but also adding a table of request_type (tv/movie), status (pending, inprogress, resolved), Title, User reported would be nice. 

**Describe alternatives you've considered**
I get notifications already, but have to visit the Ombi page to view what the issue is. While this solution works, a single point of information would be better. 

**Additional context**
/api/v1/Issues/count
/api/v1/Issues

### PR DESCRIPTION
**Pull request by anderssonoscar0**
Fixes #70 

Example Grafana table
dab6455eb75f38e5dee17d21c097bd5a

### CODE REVIEW

**Comment by DirtyCajunRice** [comment]
Hey, can you please strip this down to only an issue count? What the issues are aren’t relevant as if there are issues you need to go to Ombi to make any changes anyway. I haven’t looked at the endpoints for it but a pending, in progress and completed metric like the requests counts

**Comment by anderssonoscar0** [comment]
Hi, of course I can do that, however. 

I understand what you're saying and I personally won't use the detailed version, but others might find it useful. I'm just saying this since in the feature request @mastercpt said that a table with data would be good, and so might other users. 

Would it not be better to turn the function off in the config if a user isn't interested in a more detailed overview.  Maybe even disable it by default?




Just a thought 👍

**Comment by samwiseg0** [comment]
I agree with dirty. We are looking at this from a futures perspective. We want to make sure the project is sustainable, maintainable, and easy to use for the future. Also anything added has to be QA whenever code is modified. 

We want to make sure things we add are purposeful and well built. Having an option just because someone may want it is not in the spirit of what we want to accomplish. I am not saying this is not well built, because it is. But, it really does not serve enough of a purpose in my opinion.

**Comment by anderssonoscar0** [comment]
I understand! Removed 👍

**Comment by DirtyCajunRice** [comment]
Awesome thanks. Ok only other change I see is that since it’s just integers a structure is not needed. If you reference the Ombi requests function, getting to the proper part of the response then typecasting an int in the influx payload

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
