### PR TITLE
Added maxmind licence

### PR DESCRIPTION
**Pull request by manuelnagele**
The GeoIPHandler requires the maxmind licence key as argument.

### CODE REVIEW

**Comment by WireFuCo** [comment]
Any plans to implement this?

**Comment by samwiseg0** [comment]
This needs to be committed to develop not master.

**Comment by manuelnagele** [comment]
> This needs to be committed to develop not master.

done

**Comment by Ornias1993** [comment]
and needs to be reviewed @samwiseg0

**Comment by samwiseg0** [comment]
What is the intended purpose of this PR? T

he license key is already set in `[global]`.

**Comment by Ornias1993** [comment]
> What is the intended purpose of this PR?
> 
> The license key is already set in `[global]`.

Good point, looking at it, it can be closed.
Also design mistake to add it under tautulli settings anyway... imho.

**Pull request closed without merging**
